name: Test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.md"
      - "**.ts"
      - "**.vim"
      - "deno.jsonc"
      - ".github/workflows/test.yml"
  workflow_dispatch:
    inputs:
      denops_branch:
        description: 'Denops branch to test'
        required: false
        default: 'main'

defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail {0}

env:
  DENOPS_BRANCH: ${{ github.event.inputs.denops_branch || 'main' }}

jobs:
  check:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        deno_version:
          - "1.x"
    runs-on: ${{ matrix.runner }}
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: "${{ matrix.deno_version }}"
      - uses: actions/cache@v4
        with:
          key: deno-${{ hashFiles('**/*') }}
          restore-keys: deno-
          path: |
            /home/runner/.cache/deno/deps/https/deno.land
      - name: Lint check
        run: deno lint
      - name: Format check
        run: deno fmt --check
      - name: Type check
        run: deno task check
